/**
 * recipe.ts — verify a SynOI-signed Decision Recipe.
 *
 * Used to validate that a gateway is running an authentic recipe
 * generated by SynOI Inc, not a forked / tampered version. Pairs with
 * the gateway's recipe-loader.ts (Sprint 6) and synoi-control's
 * recipes/store.ts.
 *
 * Auditor flow:
 *
 *   const signed = await fetch(`${gw}/recipes/<id>`).then(r => r.json())
 *   // or pull the same artifact from `${cloud}/v1/recipes/<id>` directly
 *   const pubKey = await fetchSynoiPubkey()
 *   const result = verifySynoiRecipe(signed, pubKey)
 *   if (!result.valid) throw new Error(`recipe tampered: ${result.reason}`)
 *
 * What signing-key SynOI uses for recipes vs. receipts is published
 * separately; the `signer_key_id` field on the signed recipe tells
 * the verifier which key to expect.
 */

import { verify, createPublicKey } from 'node:crypto'

export interface SignedRecipe {
  payload: {
    recipe_id:     string
    version:       string
    schema:        number
    data:          Record<string, unknown>
    generated_at:  number
    refresh_after: number
  }
  signature:         string
  signer_key_id:     string
  canonical_payload: string
}

export interface RecipeVerifyResult {
  valid:        boolean
  recipe_id?:   string
  version?:     string
  signer_key_id?: string
  reason?:      string
}

/**
 * Verify SynOI's Ed25519 signature on a Decision Recipe.
 *
 * @param signed   — the signed-recipe wire shape (payload + signature +
 *                   canonical_payload + signer_key_id)
 * @param publicKey — SynOI's recipe-signing public key, either:
 *                   - base64 of raw 32 bytes (preferred)
 *                   - PEM string with SPKI structure
 *
 * Also validates that the canonical_payload matches the payload (by
 * re-canonicalizing) so a forked gateway can't ship a payload that
 * disagrees with what was actually signed.
 */
export function verifySynoiRecipe(
  signed:    SignedRecipe,
  publicKey: string,
): RecipeVerifyResult {
  try {
    if (!signed?.signature || !signed?.canonical_payload || !signed?.payload) {
      return { valid: false, reason: 'malformed signed-recipe' }
    }
    const sigBytes = Buffer.from(signed.signature, 'base64')
    if (sigBytes.length !== 64) {
      return { valid: false, reason: `Ed25519 signature must be 64 bytes; got ${sigBytes.length}` }
    }

    // Re-canonicalize the payload and confirm it matches the signed bytes.
    // This catches "I shipped a different payload than the one I signed."
    const expected = canonicalizePayload(signed.payload)
    if (expected !== signed.canonical_payload) {
      return {
        valid:  false,
        reason: 'canonical_payload does not match a re-canonicalization of payload',
      }
    }

    let keyObj: import('node:crypto').KeyObject
    if (publicKey.includes('BEGIN')) {
      keyObj = createPublicKey({ key: publicKey, format: 'pem' })
    } else {
      const rawKey = Buffer.from(publicKey, 'base64')
      if (rawKey.length !== 32) {
        return { valid: false, reason: `Ed25519 raw public key must be 32 bytes; got ${rawKey.length}` }
      }
      const spkiPrefix = Buffer.from([
        0x30, 0x2a, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, 0x03, 0x21, 0x00,
      ])
      keyObj = createPublicKey({
        key:    Buffer.concat([spkiPrefix, rawKey]),
        format: 'der',
        type:   'spki',
      })
    }

    const ok = verify(null, Buffer.from(signed.canonical_payload, 'utf-8'), keyObj, sigBytes)
    if (!ok) {
      return {
        valid:  false,
        reason: 'signature does not match canonical_payload under this public key',
      }
    }
    return {
      valid:         true,
      recipe_id:     signed.payload.recipe_id,
      version:       signed.payload.version,
      signer_key_id: signed.signer_key_id,
    }
  } catch (err) {
    return { valid: false, reason: (err as Error).message }
  }
}

/**
 * Re-canonicalize a recipe payload — alphabetically-sorted keys at every
 * level, no whitespace. Must match the server-side encoder in
 * synoi-control/src/recipes/store.ts:canonicalPayload.
 */
function canonicalizePayload(payload: Record<string, unknown>): string {
  return JSON.stringify(sortKeys(payload))
}

function sortKeys(obj: Record<string, unknown>): Record<string, unknown> {
  const sorted: Record<string, unknown> = {}
  for (const k of Object.keys(obj).sort()) {
    const v = obj[k]
    sorted[k] = (v && typeof v === 'object' && !Array.isArray(v))
      ? sortKeys(v as Record<string, unknown>)
      : v
  }
  return sorted
}
